[package]
name = "histo"
version = "0.1.0"
authors = ["frie869"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
rand = "0.6"
lamellar = { path = "../../lamellar-runtime" }

[profile.release]
opt-level=3
lto=true
codegen-units=1
debug = true 


[[bin]]
name="histo"
path="src/histo.rs"

[[bin]]
name="histo_buffered"
path="src/histo_buffered_updates.rs"

[[bin]]
name="histo_static"
path="src/histo_static.rs"

[[bin]]
name="histo_buffered_static"
path="src/histo_buffered_updates_static.rs"